name: 📦 compare-bundles

on:
  # this action will error unless run in a pr context
  pull_request:
    types: [opened, synchronize, reopened, ready_for_review]
    paths:
      - "./package.json"

concurrency:
  group: group-${{ github.ref}}
  cancel-in-progress: true

jobs:
  comment:
    name: "Comment"
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
        with:
          ref: ${{github.event.pull_request.head.ref}}

      - name: change files
        run: echo $RANDOM > ./minified-bundle-stats.json

      - name: commit using autocommit action
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          add_options: "./minified-bundle-stats.json"
          commit_message: "Updating bundle stats"
        # env:
        #   GITHUB_TOKEN: ${{secrets.MEI_TOKEN}}
