name: compare-bundles

on:
  # this action will error unless run in a pr context
  pull_request:
    types: [opened, synchronize, reopened, ready_for_review]

concurrency:
  group: group-${{ github.ref}}
  cancel-in-progress: true

jobs:
  compare:
    name: "Compare base & head bundle sizes"
    runs-on: ubuntu-latest
    permissions:
      pull-requests: write
    steps:
      - uses: actions/download-artifact@v3
      - uses: github/webpack-bundlesize-compare-action@v1.5.0
        with:
          github-token: ${{ secrets.MEI_TOKEN }}
          current-stats-json-path: ./stats-branch.json
          base-stats-json-path: ./stats-base.json
