name: compare-bundles

on:
  # this action will error unless run in a pr context
  pull_request:
    types: [opened, synchronize, reopened, ready_for_review]

concurrency:
  group: group-${{ github.ref}}
  cancel-in-progress: true

jobs:
  # Build current and upload stats.json
  # You may replace this with your own build method. All that
  # is required is that the stats.json be an artifact
  upload-stats:
    name: "Upload"
    runs-on: ubuntu-latest
    if: github.event.pull_request.draft == false
    permissions:
      contents: read
    steps:
      - uses: actions/checkout@v3
        with:
          ref: ${{github.event.pull_request.head.ref}}

      - name: Upload stats-base.json
        uses: actions/upload-artifact@v3
        with:
          name: head-stats
          path: ./stats-base.json

      - name: Upload stats-base.json
        uses: actions/upload-artifact@v3
        with:
          name: head-stats
          path: ./stats-branch.json

  compare:
    name: "Compare base & head bundle sizes"
    runs-on: ubuntu-latest
    permissions:
      pull-requests: write
    steps:
      - uses: actions/download-artifact@v3
      - uses: github/webpack-bundlesize-compare-action@v1.5.0
        with:
          github-token: ${{ secrets.MEI_TOKEN }}
          current-stats-json-path: ./head-stats/stats-branch.json
          base-stats-json-path: ./head-stats/stats-base.json
